FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
COPY ./ /app
WORKDIR /app
RUN pip install pip==19.3.1
RUN pip install -e .
CMD ["python", "-c", "from charging_api import start_api;start_api(db_config=dict(DB_CONFIG=dict(host='charging_api-db')))"]