version: '3.6'

services:

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: charging_api-db
    environment:
      - POSTGRES_DB=stations
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 5432:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"

  rest:
    build:
      context: .
      dockerfile: Dockerfile.rest
    container_name: charging_api-rest
    environment:
      - AUTH_USER=admin
      - AUTH_PW=admin
      - DB_HOST=charging_api-db
      - DB_PORT=5432
      - DB_DB=stations
      - DB_USER=docker
      - DB_PW=docker
      - DB_SCHEMA=stations
      - SRID=4326
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - db
    healthcheck:
      test: "exit 0"
